services:
  - type: web
    name: time-echo
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: APP_HOST
        sync: false
      - key: GOOD_JOB_EXECUTION_MODE
        value: async
      - key: RAILS_MAX_THREADS
        value: 5
