name: PR Size

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  size:
    name: Label PR size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Label PR size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: 10
          s_label: 'size/S'
          s_max_size: 50
          m_label: 'size/M'
          m_max_size: 250
          l_label: 'size/L'
          l_max_size: 500
          xl_label: 'size/XL'
          fail_if_xl: true
          ignored_files: 'test/**'
